project:
  type: book
  resources:
    - "images/"
    - "styles/"
    - "latex-setup.tex"
  output-dir: _output

book:
  title: "RobotZero"
  subtitle: "A Comprehensive Environment for Line-Following Robot Development"
  author: "Frank Coelho de Alcantara"
  date: "10/11/2024"
  chapters:
    - index.qmd
    - oper.qmd
    - block.qmd
    - config_layer.qmd
    - control_layer.qmd
    - testing_guide.qmd
    - references.qmd
  page-footer: "Copyright © 2024 Frank de Alcantara"
  site-url: https://frankalcantara.com
  repo-url: https://github.com/frankalcantara/linefollower
  repo-actions: [edit, issue]

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    code-background: true
    code-copy: true
    css: styles.css
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    highlight-style: github
    navigation:
      type: "numbered"
    metadata:
      twitter-card: true
      open-graph: true
      reader-mode: true
    navbar:
      background: primary
      left:
        - href: index.qmd
          text: Home
        - about.qmd
      right:
        - icon: github
          href: https://github.com/frankalcantara/linefollower

  pdf:
    documentclass: scrreprt
    papersize: a4paper
    geometry:
      - top=2.5cm
      - bottom=2.5cm
      - left=3cm
      - right=2.5cm
    fontsize: 11pt
    number-sections: true
    colorlinks: true
    latex-auto-install: true
    toc-title: "Contents"
    language: _language.yml
    include-in-header: 
      file: latex-setup.tex